apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: synthema-dev
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:${MLFLOW_VERSION}
          imagePullPolicy: IfNotPresent
          command: ["mlflow", "server"]
          args: [
            "--host", "0.0.0.0", "--port", "5000", 
            "--serve-artifacts", "--artifacts-destination", "${ARTIFACTS_DESTINATION}",
            "--backend-store-uri", "${BACKEND_STORE_URI}"
          ]
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-svc
  namespace: synthema-dev
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      protocol: TCP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#   name: dummyrest-ingress-rule
#   namespace: synthema-dev
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: mlflow.k8s.synthema.rid-intrasoft.eu
#       http:
#         paths:
#           - backend:
#               service:
#                 name: dummyrest-service
#                 port:
#                   number: 8000
#             path: /
#             pathType: Prefix
#   tls:
#     - hosts:
#         - mlflow.k8s.synthema.rid-intrasoft.eu
#       secretName: secret-tls