apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-experiment-registry-deployment
  namespace: synthema-dev
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
        - name: mlflow-setup-volume
          emptyDir: {}
      initContainers:
        - name: init-mlflow
          image: ghcr.io/mlflow/mlflow:v2.16.2
          command: [ "sh", "-c" ]
          args:
            - |
              exec pip install --no-cache-dir --only-binary=:all: \
                psycopg2-binary boto3 --target /mlflow-setup
          volumeMounts:
            - name: mlflow-setup-volume
              mountPath: /mlflow-setup
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.16.2
          imagePullPolicy: IfNotPresent
          command: [ "sh", "-c" ]
          args:
            - |
              export PYTHONPATH=/mlflow-setup && \
              exec mlflow server --backend-store-uri "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}/${POSTGRES_DB_NAME}" \
              --host 0.0.0.0 \
              --port 80 \
              --artifacts-destination "${ARTIFACTS_DESTINATION}" \
              --serve-artifacts
          volumeMounts:
            - name: mlflow-setup-volume
              mountPath: /mlflow-setup
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                key: MINIO_SECRET_KEY
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: POSTGRES_URL
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: POSTGRES_DB_NAME
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: ARTIFACTS_DESTINATION
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: ARTIFACTS_DESTINATION

          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: model-experiment-registry-service
  namespace: synthema-dev
spec:
  type: ClusterIP
  selector:
    app: model-experiment-registry-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: model-experiment-registry-ingress-rule
  namespace: synthema-dev
spec:
  ingressClassName: nginx
  rules:
    - host: mlflow.k8s.synthema.rid-intrasoft.eu
      http:
        paths:
          - backend:
              service:
                name: model-experiment-registry-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - mlflow.k8s.synthema.rid-intrasoft.eu
      secretName: secret-tls
