apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: synthema-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "mqcqwECvoga6pkDRhOUz"
  AWS_SECRET_ACCESS_KEY: "EN6t1TWZELRhn1LyGoi6ubtApmXoUJfsny9tRYz9"
  POSTGRES_USER: "barroyo"
  POSTGRES_PASSWORD: "h7J2VenS0De5WCBU"
