apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: synthema-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "Uah0Hra7U5QRqFydlF3f"
  AWS_SECRET_ACCESS_KEY: "ChQWXIVpsAxnFnD7oGBzknu1tYwrIH13nSBOoyM4"
  POSTGRES_USER: "sbarrio"
  POSTGRES_PASSWORD: "JgO01vy5Qwn01NrW1lPUphhwT3TtKKrB9UROyGPis230HEPIj7B8bpZFMkjcN2Y5"
