apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-experiment-registry-deployment
  namespace: synthema-dev
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
        - name: mlflow-setup-volume
          emptyDir: {}
      initContainers:
        - name: init-mlflow
          image: ghcr.io/mlflow/mlflow:v2.16.2
          command: [ "sh", "-c" ]
          args:
            - |
              apt-get update && apt-get install -y gcc python3-dev && \
              pip install psycopg2-binary boto3 -t /mlflow-setup
          volumeMounts:
            - name: mlflow-setup-volume
              mountPath: /mlflow-setup
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.16.2
          imagePullPolicy: IfNotPresent
          command: [ "sh", "-c" ]
          args:
            - |
              export PYTHONPATH=/mlflow-setup && \
              mlflow server --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mstorage-svc.synthema-dev:5432/mlflow \
              --host 0.0.0.0 \
              --port 80 \
              --artifacts-destination s3://mlflow \
              --serve-artifacts
          volumeMounts:
            - name: mlflow-setup-volume
              mountPath: /mlflow-setup
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: model-experiment-registries-metadata-storage-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: model-experiment-registries-metadata-storage-secret
                  key: password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: model-experiment-registries-object-storage-secret
                  key: acces_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: model-experiment-registries-object-storage-secret
                  key: secret_key
            - name: BACKEND_STORE_URI
              value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mstorage-svc.synthema-dev:5432/mlflow"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://obstorage-minio.synthema-dev:9000"
            - name: ARTIFACTS_DESTINATION
              value: "s3://mlflow"

          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: model-experiment-registry-service
  namespace: synthema-dev
spec:
  type: ClusterIP
  selector:
    app: model-experiment-registry-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: model-experiment-registry-ingress-rule
  namespace: synthema-dev
spec:
  ingressClassName: nginx
  rules:
    - host: mlflow.k8s.synthema.rid-intrasoft.eu
      http:
        paths:
          - backend:
              service:
                name: model-experiment-registry-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - mlflow.k8s.synthema.rid-intrasoft.eu
      secretName: secret-tls