apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: synthema-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio_access_key"
  AWS_SECRET_ACCESS_KEY: "minio_secret_key"
  POSTGRES_USER: "pg_user"
  POSTGRES_PASSWORD: "pg_password"
