apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: synthema-dev
type: Opaque
data:
  username: UVRkcURZV25qdUtocVZOM0RUQUk=
  password: S29XSWFzYUExcDY5WlZOdEQweElORkRSdllsZkJmTnNLZUxvVUpFSA==
---