apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: synthema-dev
type: Opaque
stringData:
  acces_key: Uah0Hra7U5QRqFydlF3f
  secret_key: ChQWXIVpsAxnFnD7oGBzknu1tYwrIH13nSBOoyM4
---